name: Release On Main Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release, without (v) prefix'
        required: true
        default: '2.0.0'

jobs:
  rebase-and-merge:
    runs-on: ubuntu-latest

    env:
      BOT_NAME: ${{ vars.BOT_NAME }}
      BOT_EMAIL: ${{ vars.BOT_EMAIL }}
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
      MAIN_BRANCH: tmp

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup GPG for signing
        uses: ./.github/actions/git-gpg-setup
        with:
          name: ${{ env.BOT_NAME }}
          email: ${{ env.BOT_EMAIL }}

      - name: Validate version
        id: validate_version
        run: |
          VERSION=${{ github.event.inputs.version }}
          
          # Check if the version matches the pattern X.Y.Z
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format. The version must match the pattern X.Y.Z" >&2
            exit 101
          fi
          
          # Fetch all tags
          git fetch --tags

          # Get the latest tag
          LATEST_TAG=$(git describe --tags "$(git rev-list --tags --max-count=1)" || echo '0.0.0')
          LATEST_TAG=${LATEST_TAG#v}
          
          # Compare versions
          if [[ $(echo -e "$LATEST_TAG\n$VERSION" | sort -V | head -n1) == "$LATEST_TAG" ]]; then
            echo "The provided version $VERSION is not greater than the latest tag $LATEST_TAG" >&2
            exit 102
          fi
          
          echo "Version $VERSION is valid and greater than the latest tag $LATEST_TAG"

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.MAIN_BRANCH }}

      - name: Rebase dev on main
        run: |
          git checkout dev
          git rebase ${{ env.MAIN_BRANCH }}

      - name: Push changes to dev
        run: |
          git push origin dev --force

      - name: Checkout main branch again
        uses: actions/checkout@v4
        with:
          ref: ${{ env.MAIN_BRANCH }}

      - name: Merge dev into main with fast-forward
        run: |
          git merge --ff-only dev

      - name: Push changes to main
        run: |
          git push origin ${{ env.MAIN_BRANCH }}

      - name: Create Tag
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_AUTHOR_NAME: ${{ env.BOT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ env.BOT_EMAIL }}
        run: |
          TAG_NAME="v${{ github.event.inputs.version }}"
          git tag -a $TAG_NAME -m "Release $TAG_NAME" --sign --file tag.sig
          git push origin $TAG_NAME
